"""Turn a verified candidate into a plan record, using the existing lesson builders.

Positions render through knowledge_lesson (the same steps as every library lesson),
catalog topics through topic_lessons, opening lines through opening_lessons (from the
learner's side), definitions through the labelled text lesson. The record has the same
shape as every other plan ({plan, course, lessons}) plus `plan.intent` (what the request
was understood to mean) and `plan.custom` (verification status and provenance).
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

import chess

from ..generator import opening_lessons, topic_lessons
from ..knowledge_lessons import CATEGORY, KNOWLEDGE_VERIFIED_BY, knowledge_lesson
from ..missing import GENERATED_VERIFIED_BY, TEXT_VERIFIED_BY, _text_lesson
from .candidate import CandidatePlan, Item, Unit

CATALOG_VERIFIED_BY = "catalog + Stockfish"
DATABASE_VERIFIED_BY = "Lichess opening database (CC0) + Stockfish, move by move"
NEW_VERIFIED_BY = "new positions checked by python-chess + Stockfish for this plan"


def example_for(item: Item, library):
    """The Example an item renders as (library/catalog: the stored one; new: built from its fields)."""
    if item.example is not None:
        return item.example
    if item.kind == "library":
        return library.get(item.ref, trusted_only=False)
    if item.kind == "catalog":
        from ..catalog import get_catalog
        from .content import catalog_example
        tid, _, pid = item.ref.partition(":")[2].partition("/")
        topic = get_catalog().topics[tid]
        pz = next(p for p in topic.puzzles if p["id"] == pid)
        return catalog_example(topic, pz, library)
    from ...knowledge.positions import replay
    from ...knowledge.schema import parse_example
    rep = replay(item.fen, item.moves)
    concept = item.concept if item.concept in library.concepts else (
        "mate_in_one" if rep.final.is_checkmate() and "mate_in_one" in library.concepts else "endgames")
    raw = {"id": "plan_new_" + uuid.uuid5(uuid.NAMESPACE_URL, item.content_key()).hex[:10], "status": "verified",
           "title": item.title or "New position", "concept": concept, "category": library.concepts[concept].category,
           "description": ("White" if chess.Board(item.fen).turn else "Black") + " to move.",
           "start_fen": item.fen, "moves": item.moves, "key_move": rep.labels[item.key_index or 0],
           "explanation": item.text or f"{rep.labels[item.key_index or 0]} is the move Stockfish confirmed.",
           "prompt": "Find the best move.", "hints": ["Look at checks, captures and threats first."],
           "presentation_modes": ["interactive", "practice"], "difficulty": max(1, min(5, item.difficulty)),
           "source": {"source_type": "plan_candidate", "source_license": "generated by ChessAI",
                      "reference": "checked by python-chess and Stockfish before use"}}
    return parse_example(raw, library.concepts, path="custom-plan", tier="generated")


def _verified_by(unit: Unit) -> str:
    provs = {i.provenance for i in unit.items}
    kinds = {i.kind for i in unit.items}
    if "definition" in kinds:
        return TEXT_VERIFIED_BY
    if "opening_line" in kinds:
        return DATABASE_VERIFIED_BY if "database" in provs else CATALOG_VERIFIED_BY
    if kinds <= {"topic"} or kinds <= {"catalog"}:
        return CATALOG_VERIFIED_BY
    if any(i.ref.startswith("gen_") for i in unit.items):
        return GENERATED_VERIFIED_BY
    if provs & {"unverified", "database"}:
        return NEW_VERIFIED_BY
    return KNOWLEDGE_VERIFIED_BY


def _category(unit: Unit, library, catalog) -> str:
    comp = unit.component
    kind = comp.get("kind")
    if kind in ("topic",) and comp.get("id") in catalog.topics:
        return catalog.topics[comp["id"]].category
    if kind in ("opening_as", "opening_db"):
        return "opening"
    if kind == "material":
        return "endgame" if comp["material"].get("head") == "endgame" else "tactic"
    if kind == "concept" and comp.get("id") in library.concepts:
        return CATEGORY.get(library.concepts[comp["id"]].category, "tactic")
    return "tactic"


def build_record(cand: CandidatePlan, report, *, library, catalog, status: str, template: dict | None = None,
                 attempts: list | None = None, note: str | None = None) -> dict:
    plan_id = uuid.uuid4().hex[:8]
    units: list[dict] = []
    lessons: list[dict] = []
    for n, unit in enumerate(cand.units, start=1):
        prefix = f"plan_{plan_id}_{n:02d}"
        new: list[dict] = []
        extra: dict = {}
        kinds = {i.kind for i in unit.items}
        if kinds == {"topic"}:
            for k, it in enumerate(unit.items):
                new += topic_lessons(prefix + (chr(97 + k) if len(unit.items) > 1 else ""), catalog.topics[it.ref])
        elif kinds == {"opening_line"}:
            for it in unit.items:
                tid = it.ref.split("@")[0]
                topic = catalog.topics.get(tid)
                if topic is not None and it.provenance == "catalog-verified":
                    summary = (f"You play {it.side.capitalize()}. This is how the {topic.title} goes — learn the "
                               f"moves from {it.side.capitalize()}'s side so you recognise it and know the replies. "
                               + topic.summary)
                    note_text = "The line is the catalog's Stockfish-checked main line, seen from the other side."
                    ideas = list(topic.ideas)
                else:
                    summary = (f"The {it.title}: its first moves, played as {it.side.capitalize()}. The line comes "
                               "from the Lichess opening database (public domain).")
                    note_text = "Every move of this line was checked by Stockfish before this lesson was made."
                    ideas = []
                new += opening_lessons(prefix, it.title, it.side, list(it.line), summary, ideas,
                                       cand.level or "beginner", verified_note=note_text)
        elif kinds == {"definition"}:
            it = unit.items[0]
            new.append(_text_lesson(prefix, unit.title, it.text, []))
        else:
            seq = [(example_for(it, library), it.role if it.role in ("demonstration", "guided", "practice")
                    else "practice") for it in unit.items]
            names = [unit.component.get("label") or unit.title]
            intro = unit.objective + (f"\n\n{unit.text}" if unit.text else "")
            intro += "\n\n" + _verification_line(unit)
            lesson = knowledge_lesson(prefix, unit.title, intro, seq,
                                      f"Lesson complete — {unit.title.split(':')[0].lower()}.", names)
            if unit.component.get("kind") == "material" and unit.component.get("material"):
                from ...lessons.requirements import material_requirements
                from ..intent.model import MaterialSpec
                spec = MaterialSpec.from_dict(unit.component["material"])
                lesson["requirements"] = material_requirements(spec, (cand.intent or {}).get("objective"),
                                                               [e for e, _ in seq])
            new.append(lesson)
            extra = {"concepts": sorted({e.concept for e, _ in seq}), "example_ids": [e.id for e, _ in seq]}
        comp = unit.component
        units.append({"topic_id": comp.get("id") if comp.get("kind") == "topic" else None, "title": unit.title,
                      "category": _category(unit, library, catalog), "reason": unit.objective,
                      "verified_by": _verified_by(unit), "lesson_ids": [ls["id"] for ls in new], **extra})
        lessons.extend(new)

    summary = cand.summary
    if note:
        summary = f"{note} {summary}".strip()
    if cand.notes:
        summary += " " + " ".join(cand.notes)
    plan = {
        "id": plan_id, "goal": cand.goal, "title": cand.title, "summary": " ".join(summary.split()),
        "created": datetime.now(timezone.utc).isoformat(timespec="seconds"), "planner": "custom", "units": units,
        "skipped": [{"title": s["title"], "reason": s["reason"]} for s in cand.skipped], "related": [],
        "intent": cand.intent,
        "custom": {
            "status": status, "proposer": cand.proposer, "fingerprint": cand.fingerprint(),
            "validated_at": report.validated_at if report else None, "checks": report.checks if report else [],
            "warnings": [i.message for i in report.issues if i.severity == "warning"] if report else [],
            "engine": report.engine if report else None, "attempts": attempts or [],
            "template_id": template["id"] if template else None, "tier": template["tier"] if template else None,
            "provenance": (template or {}).get("provenance"),
            "coverage": [{"material": c["material"]["id"], "label": c["material"]["label"],
                          "library_coverage": c["library_coverage"], "library": c["library"],
                          "generated": c["generated"]} for c in cand.coverage],
        },
    }
    course = {"id": f"plan_{plan_id}", "title": plan["title"], "description": plan["summary"], "kind": "plan",
              "lessons": [{"id": ls["id"], "title": ls["title"]} for ls in lessons]}
    return {"plan": plan, "course": course, "lessons": lessons}


def _verification_line(unit: Unit) -> str:
    vb = _verified_by(unit)
    if vb == KNOWLEDGE_VERIFIED_BY:
        return "Every position comes from the verified Knowledge Library (checked by python-chess and Stockfish)."
    if vb == CATALOG_VERIFIED_BY:
        return "Every puzzle is from real games and was checked by Stockfish."
    if vb == GENERATED_VERIFIED_BY and any(i.ref.startswith("gen_material_") for i in unit.items):
        return ("These positions were generated for this request and verified: python-chess (legal, exactly the "
                "requested pieces for each side) and Stockfish (the best move works, natural alternatives are worse).")
    return "Every position here was checked by python-chess (legal) and Stockfish (the solution works) before use."
